services:
  frontend:
    container_name: frontend
    image: node:22-slim
    working_dir: /home/node/app
    command: /bin/sh -c 'npm config set strict-ssl false && npm install && npm run dev'
    ports:
      - '3000:3000'
    volumes:
      - './frontend:/home/node/app'

  backend:
    container_name: backend
    image: node:22-slim
    working_dir: /home/node/app
    command: /bin/sh -c 'npm config set strict-ssl false && npm install && node --loader ts-node/esm src/server.ts'
    ports:
      - '3001:3001'
    volumes:
      - './backend:/home/node/app'
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase

  database:
    container_name: database
    image: mongo:latest
    ports:
      - '27017:27017'
