services:
  # frontend:
  #   container_name: frontend
  #   image: node:22-slim
  #   working_dir: /home/node/app
  #   command: /bin/sh -c 'npm config set strict-ssl false && npm install && npm run dev'
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - './frontend:/home/node/app'

  backend:
    container_name: backends
    image: node:22-slim
    working_dir: /home/node/app
    command: /bin/sh -c 'npm config set strict-ssl false && npm install && npm run start'
    ports:
      - '3001:3001'
    volumes:
      - './backend:/home/node/app'
    environment:
      - MONGO_URI=mongodb://mongo:27017/db_ecommerce

  database:
    container_name: database
    image: mongo:latest
    ports:
      - '27017:27017'
