version: '3.8'

services:
  node:
    container_name: next
    image: node:22-slim
    working_dir: /home/node/app
    command: /bin/sh -c 'npm install && npm run dev'
    ports:
      - '3000:3000'
    volumes:
      - './:/home/node/app'
